name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed

env:
  REGISTRY: registry.digitalocean.com/mohammedbabiker
  IMAGE_NAME: "mohammedbabiker"
  IMAGE_TAG: ${{ github.sha }}
  REPOSITORY: mohammedbabiker

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: login into container registry
        run: doctl registry login --expiry-seconds 600
        # run: docker login registry.digitalocean.com --username ${{ secrets.DO_REGISTRY_TOKEN }} --password ${{ secrets.DO_REGISTRY_TOKEN }}

      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Build image
        run: |
          docker build . -t $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Push image
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to Server via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }},GITHUB_SHA
          port: ${{ secrets.PORT }}
          script: |
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            docker pull $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
